import { Metadata } from 'next';
import { notFound } from 'next/navigation';
import CaseDetail from '@/components/casos/CaseDetail';
import { api } from '@/lib/api';
import { generateBreadcrumbSchema, generateCaseStudySchema } from '@/lib/schemas';

interface PageProps {
    params: Promise<{
        slug: string;
    }>;
}

export async function generateStaticParams() {
    const { cases } = await api.cases.getPageData();
    return cases.map((caseStudy) => ({
        slug: caseStudy.slug,
    }));
}

export async function generateMetadata({ params }: PageProps): Promise<Metadata> {
    const { slug } = await params;
    const { caseStudy } = await api.cases.getDetailPageData(slug);

    if (!caseStudy) {
        return {
            title: 'Caso no encontrado | Datify',
        };
    }

    return {
        title: `${caseStudy.title} | Casos de Éxito Datify`,
        description: caseStudy.description,
        alternates: {
            canonical: `/casos/${slug}`,
        },
        openGraph: {
            type: 'article',
            url: `https://godatify.com/casos/${slug}`,
            title: `${caseStudy.title} | Casos de Éxito Datify`,
            description: caseStudy.description,
            // Image auto-generated by opengraph-image.tsx
        },
    };
}

export default async function CaseDetailPage({ params }: PageProps) {
    const { slug } = await params;
    const { caseStudy, relatedCases } = await api.cases.getDetailPageData(slug);

    if (!caseStudy) {
        notFound();
    }

    return (
        <main id="main-content">
            {/* Breadcrumb Schema */}
            <script
                type="application/ld+json"
                dangerouslySetInnerHTML={{
                    __html: JSON.stringify(generateBreadcrumbSchema([
                        { name: 'Inicio', url: 'https://godatify.com/' },
                        { name: 'Casos de Éxito', url: 'https://godatify.com/casos' },
                        { name: caseStudy.title }
                    ]))
                }}
            />
            
            {/* CaseStudy Article Schema */}
            <script
                type="application/ld+json"
                dangerouslySetInnerHTML={{
                    __html: JSON.stringify(generateCaseStudySchema(caseStudy, slug))
                }}
            />
            
            <CaseDetail caseStudy={caseStudy} relatedCases={relatedCases} />
        </main>
    );
}
