import { api } from "@/lib/api";
import RichTextRenderer from "@/components/blog/RichTextRenderer";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import BlogCTA from "@/components/blog/BlogCTA";
import BlogCard from "@/components/blog/BlogCard";
import RelatedServices from "@/components/blog/RelatedServices";
import Icon from "@/components/ui/Icon";
import styles from "./page.module.css";
import { Metadata } from "next";
import { formatDate } from "@/lib/formatDate";
import { generateArticleSchema, generateBreadcrumbSchema } from "@/lib/schemas";
import { getRelatedServiceSlugs } from "@/lib/tagServiceMap";

import { BLOG_STATIC_DATA } from "@/data/blog-data";

interface Props {
    params: Promise<{ slug: string }>;
}

export async function generateStaticParams() {
    const posts = await api.blog.getAll();
    return posts.map((post) => ({
        slug: post.slug,
    }));
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
    const { slug } = await params;
    const post = await api.blog.getBySlug(slug);

    if (!post) {
        return {
            title: BLOG_STATIC_DATA.metadata.notFoundTitle,
        };
    }

    return {
        title: `${post.title}${BLOG_STATIC_DATA.metadata.titleSuffix}`,
        description: post.excerpt,
        alternates: {
            canonical: `/blog/${slug}`,
        },
        openGraph: {
            title: post.title,
            description: post.excerpt,
            type: 'article',
            publishedTime: post.date,
            authors: [post.author.name],
            // Image auto-generated by opengraph-image.tsx
        },
    };
}

export default async function BlogPostPage({ params }: Props) {
    const { slug } = await params;
    const post = await api.blog.getBySlug(slug);

    if (!post) {
        notFound();
    }

    const allPosts = await api.blog.getAll();
    const relatedPosts = allPosts
        .filter((p) => p.id !== post.id && p.tags.some((tag) => post.tags.includes(tag)))
        .slice(0, 3);

    // Get related services based on post tags
    const allServices = await api.services.getAll();
    const relatedServiceSlugs = getRelatedServiceSlugs(post.tags);
    const relatedServices = allServices.filter((s) => 
        s.slug && relatedServiceSlugs.includes(s.slug)
    );

    return (
        <article className={styles.articleContainer}>
            <div className="container mx-auto px-6">
                <Link href="/blog" className={styles.backLink}>
                    <Icon name="arrow-left" /> {BLOG_STATIC_DATA.detail.back}
                </Link>

                <header className={styles.hero}>
                    <div className={styles.tags}>
                        {post.tags.map((tag, idx) => (
                            <span key={idx} className={styles.tag}>{tag}</span>
                        ))}
                    </div>

                    <h1 className={styles.title}>{post.title}</h1>

                    <div className={styles.meta}>
                        <div className={styles.author}>
                            {post.author.image ? (
                                <Image
                                    src={post.author.image}
                                    alt={post.author.name}
                                    width={48}
                                    height={48}
                                    className={styles.authorImage}
                                />
                            ) : (
                                <div className={styles.authorPlaceholder} />
                            )}
                            <div>
                                <span className={styles.authorName}>{post.author.name}</span>
                                <span className={styles.authorRole}>{post.author.role}</span>
                            </div>
                        </div>
                        <div className={styles.metaDivider}></div>
                        <div className={styles.dateInfo}>
                            <span className={styles.dateLabel}>{BLOG_STATIC_DATA.detail.published}</span>
                            <span className={styles.dateValue}>{formatDate(post.date)} · {post.readingTime} {BLOG_STATIC_DATA.detail.readingTime}</span>
                        </div>
                    </div>
                </header>

                <div className={styles.featuredImageWrapper}>
                    <Image
                        src={post.image}
                        alt={post.title}
                        fill
                        className={styles.featuredImage}
                        priority
                    />
                </div>

                {/* Article Schema */}
                <script
                    type="application/ld+json"
                    dangerouslySetInnerHTML={{
                        __html: JSON.stringify(generateArticleSchema(post, slug))
                    }}
                />

                {/* Breadcrumb Schema */}
                <script
                    type="application/ld+json"
                    dangerouslySetInnerHTML={{
                        __html: JSON.stringify(generateBreadcrumbSchema([
                            { name: 'Inicio', url: 'https://godatify.com/' },
                            { name: 'Blog', url: 'https://godatify.com/blog' },
                            { name: post.title }
                        ]))
                    }}
                />


                <div className={styles.content}>
                    <RichTextRenderer content={post.content} />
                    <div className={styles.ctaWrapper}>
                        <BlogCTA />
                    </div>
                    <RelatedServices services={relatedServices} />
                </div>

                {relatedPosts.length > 0 && (
                    <div className={styles.relatedSection}>
                        <h2 className={styles.relatedTitle}>{BLOG_STATIC_DATA.related.title}</h2>
                        <div className={styles.relatedGrid}>
                            {relatedPosts.map((relatedPost) => (
                                <div key={relatedPost.id} className={styles.relatedCardWrapper}>
                                    <BlogCard post={relatedPost} />
                                </div>
                            ))}
                        </div>
                    </div>
                )}
            </div>
        </article>
    );
}
