import type { Metadata } from "next";

const siteConfig = {
    name: "Datify",
    url: "https://godatify.com",
    description: "Transformamos datos en decisiones de negocio. Consultoría especializada en Data Analytics, BI y AI para empresas en LATAM. →",
    locale: "es_PE",
};

export const defaultMetadata: Metadata = {
    metadataBase: new URL(siteConfig.url),
    robots: {
        index: true,
        follow: true,
        googleBot: {
            index: true,
            follow: true,
            'max-video-preview': -1,
            'max-image-preview': 'large',
            'max-snippet': -1,
        },
    },
    title: {
        default: `${siteConfig.name} – Datificando las Organizaciones`,
        template: `%s | ${siteConfig.name}`,
    },
    description: siteConfig.description,
    keywords: [
        "consultoría de datos",
        "data analytics",
        "business intelligence",
        "big data",
        "data engineering",
        "inteligencia artificial",
        "machine learning",
        "transformación digital",
        "análisis de datos Perú",
        "consultora de datos LATAM",
        "BI empresarial",
        "datify",
    ],
    authors: [{ name: siteConfig.name, url: siteConfig.url }],
    creator: siteConfig.name,
    publisher: siteConfig.name,
    formatDetection: {
        email: false,
        address: false,
        telephone: false,
    },
    alternates: {
        canonical: '/',
        languages: {
            'es-PE': '/',
            'es-ES': '/',
        },
    },
    verification: {
        google: process.env.NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION || '',
    },
    category: 'technology',
    classification: 'Data Consultancy',
    icons: {
        icon: [
            { url: '/images/favicon.png', type: 'image/png', sizes: '32x32' },
            { url: '/favicon.ico', sizes: 'any' },
        ],
        apple: { url: '/images/favicon.png', sizes: '180x180' },
    },
    openGraph: {
        type: "website",
        locale: siteConfig.locale,
        url: siteConfig.url,
        siteName: siteConfig.name,
        title: `${siteConfig.name} – Datificando las Organizaciones`,
        description: siteConfig.description,
        images: [
            {
                url: `${siteConfig.url}/images/og-image.png`,
                width: 1200,
                height: 630,
                alt: `${siteConfig.name} - Data Transformation Leaders`,
            },
        ],
    },
    twitter: {
        card: "summary_large_image",
        site: "@godatify",
        creator: "@godatify",
        title: `${siteConfig.name} - Datificando las Organizaciones`,
        description: siteConfig.description,
        images: [`${siteConfig.url}/images/og-image.png`],
    },
};

/**
 * Helper for generating page-specific metadata with canonical URL
 * OG images are auto-generated by opengraph-image.tsx files
 * 
 * @param title - Page title (will be appended with site name for OG)
 * @param description - Page description for SEO and OG
 * @param path - URL path (e.g., '/nosotros')
 * @param options - Optional configuration
 * @param options.type - OG type (defaults to 'website')
 */
export function generatePageMetadata(
    title: string,
    description: string,
    path: string,
    options?: {
        type?: 'website' | 'article' | 'profile';
    }
): Metadata {
    const url = `${siteConfig.url}${path}`;
    const ogType = options?.type || 'website';

    return {
        title,
        description,
        alternates: {
            canonical: path,
        },
        openGraph: {
            type: ogType,
            title: `${title} | ${siteConfig.name}`,
            description,
            url,
            // Image auto-generated by opengraph-image.tsx
        },
    };
}
